### ISSUE TITLE
Write from bash script in Alfred-accessible variable

### ISSUE THREAD

**Issue by robimac04** [shawnrice/alfred-documentation#5]
Hi,

I have a question to variables. I've created a bash script within a workflow.  This script creates an output. And now I want to save this output in a variable from Alfred to work with this value in the workflow. 

Does anyone have an idea how to achieve this?

Thanks you.

**Comment by deanishe** [comment]
It's a much better idea to ask questions like this on the Alfred forums.

This post might help: https://www.alfredforum.com/topic/9070-how-to-workflowenvironment-variables/
